name: Create release on push to main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP package
        run: |
          mkdir -p artifacts
          zip -r artifacts/desqueezer.zip \
            Desqueezer.lrdevplugin/Info.lua \
            Desqueezer.lrdevplugin/Main.lua \
            Desqueezer.lrdevplugin/scripts/desqueezer.sh

      - name: Determine next version by date
        id: tag
        run: |
          SAFE_TAG=$(date +"%H-%M_%d-%m-%Y")
          RELEASE_NAME=$(date +"%H:%M, %d %m %Y")
          echo "new_tag=$SAFE_TAG" >> $GITHUB_OUTPUT
          echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: ${{ steps.tag.outputs.release_name }}
          artifacts: artifacts/desqueezer.zip
          allowUpdates: true
          replacesArtifacts: true