name: Create release on push to master

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP package
        run: |
          mkdir -p artifacts
          zip -r artifacts/desqueezer.zip \
            Desqueezer.lrdevplugin/Info.lua \
            Desqueezer.lrdevplugin/Main.lua \
            Desqueezer.lrdevplugin/scripts/desqueezer.sh

      - name: Set release name with date
        run: |
          echo "RELEASE_NAME=Release $(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: ${{ env.RELEASE_NAME }}
          artifacts: artifacts/desqueezer.zip
          allowUpdates: true
          replacesArtifacts: true